### ISSUE TITLE
any proposal process?

### ISSUE THREAD

**Issue by AndyChanWeb3** [BtcName/BtcName#1]
if I want to propose a proposal, what process should I follow like BIP?

**Comment by wanshan2048** [comment]
see here : https://github.com/BtcName/BtcName/blob/main/README.md#how-to-submit-proposal

**Comment by AndyChanWeb3** [comment]
I mean process like BIP for bitcoin or EIP for ens, not GitHub working flow?

**Comment by wanshan2048** [comment]
How to submit proposal?
Step 1: fork this repository
Step 2: write your proposal in [proposal](https://github.com/BtcName/BtcName/blob/main/proposal) directory
Step 3: submit your pr
Step 4: BtcName community review
