### ISSUE TITLE
remove case 4 in specification

### ISSUE THREAD

**Issue by AndyChanWeb3** [BtcName/BtcName#2]
https://docs.btcname.id/docs/ordinals-primary-name-protocol/ordinals-primary-name-protocol-solution-b-beta#id-3.-some-cases

I don't think we should define how to deal with other name ordinals here, reason for these:

- how to deal with other name system should be handle by the up level applications, not included in primary BTCName
- not to give .sats attention

And I have no interests in support .sats as domain name.

**Comment by wanshan2048** [comment]
Thanks for your suggestion.

Removed .sats from docs.
