### ISSUE TITLE
Add specification for override primary data

### ISSUE THREAD

**Issue by AndyChanWeb3** [BtcName/BtcName#3]
Add case in the specification that:

- a.btc been set as primary BTCName
- b.btc been set as primary BTCName
- b.btc been transferred out

is that a.btc still primary BTCName for that address?

I suggest make the override data invalid, which is the answer: No.

**Comment by wanshan2048** [comment]
a.btc is not  primary BTCName for this case.

**Comment by wanshan2048** [comment]
Thanks for your suggestion.

case 4: Wallet A owns "a.btc", "b.btc". Wallet A first transfer a.btc to itself, then transfer "b.btc" to itself, then transfer "b.btc" to Wallet B. At this point, Wallet A does not have a Primary Name.

docs updated.  https://docs.btcname.id/docs/ordinals-primary-name-protocol/ordinals-primary-name-protocol-solution-b-beta
